- name: Install dependencies
        run: |
          npm install
      - name: Change permissions
        run: |
          chmod +x ./node_modules/.bin/mocha
      - name: Run tests
        run: |
          npm test

