name: Node.js CI

on:
  push:
    branches:
      - main  # Only run workflow on pushes to main branch
  pull_request:
    branches:
      - main  # Run workflow for PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js version 16

      - name: Install dependencies
        run: |
          yarn install  # Or use: npm install

      - name: Run tests
        run: |
          yarn test  # Or use: npm test

